"""Small DB-API compatibility layer for SQLite locally and PostgreSQL online.

The project started as a self-contained SQLite demo.  Render does not retain
local files after a restart, so the deployed app uses the single PostgreSQL
database supplied by Supabase.  The application code can keep the familiar
``connection.execute(...).fetchone()`` form in both environments.
"""

from __future__ import annotations

import re
import sqlite3
from collections.abc import Iterable
from typing import Any

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:  # pragma: no cover - only reached when production dependency is missing.
    psycopg = None
    dict_row = None


DATABASE_INTEGRITY_ERRORS = (
    sqlite3.IntegrityError,
    *((psycopg.IntegrityError,) if psycopg is not None else ()),
)

_POSTGRES_PREFIXES = ("postgres://", "postgresql://")
_PRAGMA_TABLE_INFO = re.compile(r"^\s*PRAGMA\s+table_info\((?P<table>[A-Za-z_][A-Za-z0-9_]*)\)\s*$", re.IGNORECASE)
_SQLITE_IDENTITY = re.compile(r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b", re.IGNORECASE)


def is_postgres_database(database_target: str) -> bool:
    return database_target.strip().lower().startswith(_POSTGRES_PREFIXES)


class CompatRow(dict):
    """Mapping row that also retains SQLite's ``row[0]`` convenience."""

    def __getitem__(self, key: Any):
        if isinstance(key, int):
            return list(self.values())[key]
        return super().__getitem__(key)


class PostgresCursor:
    def __init__(self, connection: "PostgresConnection") -> None:
        self._connection = connection
        self._cursor = None
        self.lastrowid: int | None = None
        self.rowcount = -1

    def execute(self, statement: str, parameters: Iterable[Any] | None = None):
        query, parameters = self._connection.prepare(statement, parameters)
        self._cursor = self._connection.raw_connection.cursor(row_factory=dict_row)
        self._cursor.execute(query, parameters)
        self.rowcount = self._cursor.rowcount
        if self._connection.insert_returns_id(statement):
            generated = self._cursor.fetchone()
            self.lastrowid = int(generated["id"]) if generated else None
        return self

    def fetchone(self):
        if self._cursor is None:
            return None
        row = self._cursor.fetchone()
        return CompatRow(row) if row is not None else None

    def fetchall(self):
        if self._cursor is None:
            return []
        return [CompatRow(row) for row in self._cursor.fetchall()]


class PostgresConnection:
    """Expose the minimal sqlite3 connection API used by this project."""

    def __init__(self, database_url: str) -> None:
        if psycopg is None:  # pragma: no cover - dependency validated in deployment.
            raise RuntimeError("Thiếu psycopg. Hãy cài dependencies từ requirements.txt trước khi dùng PostgreSQL.")
        self.raw_connection = psycopg.connect(database_url, row_factory=dict_row)

    def cursor(self) -> PostgresCursor:
        return PostgresCursor(self)

    def execute(self, statement: str, parameters: Iterable[Any] | None = None) -> PostgresCursor:
        return self.cursor().execute(statement, parameters)

    def prepare(self, statement: str, parameters: Iterable[Any] | None) -> tuple[str, Iterable[Any] | None]:
        pragma_match = _PRAGMA_TABLE_INFO.match(statement)
        if pragma_match:
            return (
                "SELECT column_name AS name FROM information_schema.columns "
                "WHERE table_schema = 'public' AND table_name = %s ORDER BY ordinal_position",
                (pragma_match.group("table"),),
            )

        query = _SQLITE_IDENTITY.sub("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", statement)
        query = query.replace("?", "%s")
        if self.insert_returns_id(statement):
            query = query.rstrip().rstrip(";") + " RETURNING id"
        return query, parameters

    @staticmethod
    def insert_returns_id(statement: str) -> bool:
        return bool(re.match(r"^\s*INSERT\s+INTO\s+", statement, re.IGNORECASE))

    def commit(self) -> None:
        self.raw_connection.commit()

    def rollback(self) -> None:
        self.raw_connection.rollback()

    def close(self) -> None:
        self.raw_connection.close()


def connect_database(database_target: str):
    """Return a PostgreSQL connection for a URL or SQLite for a local path."""
    if is_postgres_database(database_target):
        return PostgresConnection(database_target)
    connection = sqlite3.connect(database_target)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA foreign_keys = ON")
    return connection
